### PR TITLE
Publishable package

### LINKED ISSUE #264: Make the package publishable
As a StarkNet smart contract developer, I want to import the `protostar` package as a python dependency to use it in my tooling suite.

### PR DESCRIPTION
**Pull request by Bernardstanislas**
This closes #264.

A python mostly-followed best-practice is to name the main folder after your package name. This is what I did here.

I then tried to package it with `poetry build`, everything runs fine.
The package is usable in another project, which is perfect.

I might have squatted by accident the `protostar` namespace in version `0.2.0` on TestPypi, let me know if you have issues because of this, we can figure out a solution.

### CODE REVIEW

**Comment by kasperski95** [comment]
It doesn't hurt to rename `src` to `protostar`. However, I am not sure whether we should publish Protostar in this form as the python package.
@MaksymilianDemitraszek  WDYT?

**Comment by Bernardstanislas** [comment]
@MaksymilianDemitraszek I changed the base branch back to master because I feel you'll get a lot of conflicts merging development into master otherwise, WDYT?
If that's fine, this is ready for review

**Comment by MaksymilianDemitraszek** [comment]
@Bernardstanislas yup it's ok, we are getting rid of development branch, leaving only master

**Comment by Bernardstanislas** [comment]
I have to keep up with your updates on `master` haha
Rebasing now, let me know if the base branch is stable so that you can merge this one

**Comment by Bernardstanislas** [comment]
Up to date!

**Pull request merged**
