### PR TITLE
Drop the warning for unstable feature in fuzzing

### LINKED ISSUE #1021: Remove unstable feature badge from fuzzing docs
It's high time to drop this IMHO:
image

### PR DESCRIPTION
**Pull request by Arcticae**
closes #1021

### CODE REVIEW

**Review by mkaput — APPROVED** [review]
Looks good, but I think we should merge this in >= v0.8 release window, because @karol-bisztyga has introduced a breaking change in #995

**Review by mkaput — CHANGES_REQUESTED** [review]
blocking PR just in case because of that reason

**Comment by karol-bisztyga** [comment]
#1008

**Comment by Arcticae** [comment]
@karol-bisztyga it's been released today, hasn't it?

**Comment by karol-bisztyga** [comment]
> @karol-bisztyga it's been released today, hasn't it?

Not sure what you mean.
In #995 we just show a warning - this was indeed merged in [v0.7.0](https://github.com/software-mansion/protostar/releases/tag/v0.7.0)
In #1008 we raise an error - this will be merged in [0.8](https://github.com/software-mansion/protostar/milestone/23)

**Comment by mkaput** [comment]
Hmm, I didn't think about this in such terms. I thought that we can remove this warning given that #1008 will land in the same release. But maybe we should indeed wait one cycle more just in case...

**Comment by Arcticae** [comment]
Moving this to 0.9

**Review by mkaput — APPROVED** [review]

**Review by karol-bisztyga — APPROVED** [review]

**Pull request merged**
