### PR TITLE
Cleanup tests

### LINKED ISSUE #1696: Cairo1 tests directory structure
We need to provide a solid directory structure for cairo1 runer tests

Currently those are scatterd between
`tests/integration/cairo1`
`tests/integration/cairo1_compiler_bindings`
`tests/integration/pure_cairo_vm`

### PR DESCRIPTION
**Pull request by cptartur**
Closes #1696

### CODE REVIEW

**Review by karol-bisztyga — COMMENTED** [review]
How about doing `tests/integration/cairo1` instead of `tests/integration/cairo1_tests`, it's obvious there are going to be tests there, right?

Also, why `commands` dir is outside of the main Cairo 1 directory (next to it to be precise)? I'd put it inside of it.

**Comment by cptartur** [comment]
> How about doing `tests/integration/cairo1` instead of `tests/integration/cairo1_tests`, it's obvious there are going to be tests there, right?

Eventually I want to name it just `cairo1`, but the directory like this already exists so resolving possible conflicts between this PR and master is not going to be nice. I'll rename it before the merge.

> Also, why `commands` dir is outside of the main Cairo 1 directory (next to it to be precise)? I'd put it inside of it.

There are commands which aren't directly related to cairo1 and I don't think it makes much sense to split it between cairo0 and 1 commands directories, since some are shared between versions.

**Review by karol-bisztyga — APPROVED** [review]
Ok, cool. I'm going to accept, the idea is obviously right, and the implementation should be alright with what's been said here. I believe that it's about to be satisfying.

**Review by Arcticae — DISMISSED** [review]

**Comment by MaksymilianDemitraszek** [comment]
Can we prioritize merging this one above anything elese? It will be very prone to merge conflicts

**Review by Arcticae — DISMISSED** [review]

**Pull request merged**
