### PR TITLE
Use pytest-xdist to further parallelize tests

### PR DESCRIPTION
**Pull request by mkaput**
https://pytest-xdist.readthedocs.io/en/latest/distribution.html

### CODE REVIEW

**Comment by Arcticae** [comment]
@mkaput Does this work properly with coverage?

**Comment by mkaput** [comment]
> @mkaput Does this work properly with coverage?

Probably not, but I primarily want to experiment if this helps at all, because default `auto` mode does not gain anything...

**Review by kasperski95 — COMMENTED** [review]
If codecov is a problem, I'd remove it in favor of faster checks.

**Comment by mkaput** [comment]
Now coverage is disabled @Arcticae @kasperski95

**Comment by Arcticae** [comment]
@mkaput is this one ready? does it introduce a speedup?

**Comment by mkaput** [comment]
Yep, not as much as I anticipated, but still few minutes better.

**Review by Arcticae — APPROVED** [review]

**Pull request merged**
