### PR TITLE
Redesigning `protostar.toml` 18 — Connect compatibility checker

### PR DESCRIPTION
**Pull request by kasperski95**
Display warnings if a Protostar project is not compatible with Protostar.
Related #477

### CODE REVIEW

**Review by Arcticae — CHANGES_REQUESTED** [review]
I don't understand why we validate this. This only makes the user confused when he upgrades protostar, and changes in a new version might not be even breaking the behavior of config file.

**Comment by kasperski95** [comment]
> I don't understand why we validate this. This only makes the user confused when he upgrades protostar, and changes in a new version might not be even breaking the behavior of config file.

The behavior of the configuration file doesn't have to change, but the behavior of cheatcodes can. The change doesn't have to be breaking to introduce unexpected behavior.

**Comment by Arcticae** [comment]
I'm not convinced. Going to leave it up to @mkaput

**Review by mkaput — APPROVED** [review]
@kasperski95 intentions are convincing to me, but I definitely would love to hear community feedback on this. Indeed, for some people this will be only unwanted burden at current stage of Protostar when users probably catch up new releases quickly.

**Comment by kasperski95** [comment]
Currently, the checker will only print a warning. It shouldn't be intrusive, yet it gives an initiative to keep the declaration valid. Without the checker, there's no point of keeping `protostar-version` in the configuration file because it can be invalid.

**Comment by mkaput** [comment]
Yup, I agree with your point and this code is fine to me!

**Pull request merged**
