### PR TITLE
Delete obsolete use_cairo_test_runner

### PR DESCRIPTION
**Pull request by karol-bisztyga**

### CODE REVIEW

**Comment by MaksymilianDemitraszek** [comment]
@Arcticae 
We can either skip them or just us this PR as a reference in the future, this code will not disapear, that is the power of git

**Review by Arcticae — APPROVED** [review]
> Also, if this runner is obsolete we should probably merge cairo1 adapter with the runner. 

Can we restrain from merging this without refactoring this?
I think there's not much happening in this PR anyway and i'd rather have this done in one go. 
I won't block you though, just if you want to merge deleting tests separately.

**Comment by Arcticae** [comment]
@karol-bisztyga can you take a look as well?

**Review by karol-bisztyga — COMMENTED** [review]
Looks ok

**Comment by MaksymilianDemitraszek** [comment]
@karol-bisztyga @Arcticae can we merge this one?

**Pull request merged**
